# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-node:
    runs-on: self-hosted
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: amineb01/sopptas

      - name: Remove old containers
        #run: docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
        run: docker-compose down
      - name: Create env file
        run: |
          touch .env
          echo PORT=3000 >> .env
          echo SERVER=0.0.0.0 >> .env
          echo GOOGLE_USER=${{ secrets.GOOGLE_USER }} >> .env
          echo GOOGLE_PASS=${{ secrets.GOOGLE_PASS }} >> .env
          echo DB_SERVER=mongo >> .env
          echo DB_PORT=27017 >> .env
          echo privateKey=${{ secrets.SECRET_KEY }} >> .env
          cat .env 
      - name: cp env
        run: cp .env ./backend
      - name: run docker compose
        run: docker-compose up --build -d  

      - name: Sleep for 20 seconds and seed db
        #   |
        #   sleep 20
        #   mongorestore --host 0.0.0.0 --db sopptas ./backend/db-fixture/dump/soppta
        run: mongorestore --host 0.0.0.0 --db sopptas ./backend/db-fixture/dump/sopptas
        env:
          CD: true
